=== antunonline/azfcms/library/Azf/Template/template.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           xmlns="http://it-branch.com/xml/ns/template.xsd"
           targetNamespace="http://it-branch.com/xml/ns/template.xsd"
>
    <xs:element name="template" type="template"></xs:element>
    <xs:complexType name="template">
        <xs:all >
            <xs:element name="name" type="xs:string"></xs:element>
            <xs:element name="description" type="xs:string"></xs:element>
            <xs:element name="identifier" type="xs:Name"></xs:element>
            <xs:element name="regions" type="regions"></xs:element>
        </xs:all>  
    </xs:complexType>
    <xs:complexType name="regions">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="region" type="region"></xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="region">
        <xs:all >
            <xs:element name="name" type="xs:string"/>
            <xs:element name="identifier" type="xs:Name"/>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== antunonline/azfcms/tests/library/Azf/Template/resources/Another Valid Template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<template
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://it-branch.com/xml/ns/template.xsd'
    xsi:schemaLocation='http://it-branch.com/xml/ns/template.xsd file:/var/www/azfcms/library/Azf/Template/template.xsd'>
    <name>Another Template</name>
    <description>Another Template Description</description>
    <identifier>anotherTemplate</identifier>
    <regions>
        <region>
            <name>Left Region</name>
            <identifier>leftRegion</identifier>
        </region>
        <region>
            <name>Right Region</name>
            <identifier>rightRegion</identifier>
        </region>
    </regions>

</template>

=== antunonline/azfcms/application/configs/descriptor/template/GreenTree.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<template
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://it-branch.com/xml/ns/template.xsd'
    xsi:schemaLocation='http://it-branch.com/xml/ns/template.xsd file:/var/www/azfcms/library/Azf/Template/template.xsd'>
    <name>Green Tree</name>
    <description>Green theme template</description>
    <identifier>greenTree</identifier>
    <regions>
        <region>
            <name>Header</name>
            <identifier>header</identifier>
        </region>
        <region>
            <name>Left</name>
            <identifier>left</identifier>
        </region>
    </regions>

</template>

=== antunonline/azfcms/application/configs/descriptor/template/demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<template
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://it-branch.com/xml/ns/template.xsd'
    xsi:schemaLocation='http://it-branch.com/xml/ns/template.xsd file:/var/www/azfcms/library/Azf/Template/template.xsd'>
    <name>Demo Template</name>
    <description>Demo Template used for testing</description>
    <identifier>demo</identifier>
    <regions>
        <region>
            <name>Demo 1</name>
            <identifier>demo1</identifier>
        </region>
        <region>
            <name>Demo 2</name>
            <identifier>demo2</identifier>
        </region>
    </regions>

</template>

=== antunonline/azfcms/tests/library/Azf/Template/resources/ValidTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<template
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://it-branch.com/xml/ns/template.xsd'
    xsi:schemaLocation='http://it-branch.com/xml/ns/template.xsd file:/var/www/azfcms/library/Azf/Template/template.xsd'>
    <name>Valid Template</name>
    <description>Valid Template Description</description>
    <identifier>validTemplate</identifier>
    <regions>
        <region>
            <identifier>header</identifier>
            <name>Header Region</name>
        </region>
    </regions>

</template>

=== antunonline/azfcms/application/configs/descriptor/template/tmpl8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<template
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://it-branch.com/xml/ns/template.xsd'
    xsi:schemaLocation='http://it-branch.com/xml/ns/template.xsd file:/var/www/azfcms/library/Azf/Template/template.xsd'>
    <name></name>
    <description>Template8</description>
    <identifier>tmpl8</identifier>
    <regions>
        <region>
            <name>Izbornik alata</name>
            <identifier>toolboxMenu</identifier>
        </region>
        <region>
            <name>Left Above Menu</name>
            <identifier>leftAboveMenu</identifier>
        </region>
        <region>
            <name>Left Below Menu</name>
            <identifier>leftBelowMenu</identifier>
        </region>
        <region>
            <name>Before Body</name>
            <identifier>beforeBody</identifier>
        </region>
        <region>
            <name>Below Body</name>
            <identifier>belowBody</identifier>
        </region>
    </regions>

</template>
