=== antunonline/azfcms/library/Azf/Plugin/Descriptor/Parser/Content.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://it-branch.com/xml/ns/plugin/content"
           xmlns="http://it-branch.com/xml/ns/plugin/content"
           elementFormDefault="qualified"
>
    <xs:element name="plugin" type="Plugin" />
    <xs:complexType name="Plugin" >
        <xs:sequence >
            <xs:element name="pluginIdentifier" minOccurs="1" maxOccurs="1"  type="xs:string"></xs:element>
            <xs:element name="displayName" minOccurs="1" maxOccurs="1"  type="xs:string"></xs:element>
            <xs:element name="description" minOccurs="1" maxOccurs="1" type="xs:string"></xs:element>
            <xs:element name="version"  maxOccurs="1" minOccurs="0" type="xs:decimal"></xs:element>
            <xs:element name="module" minOccurs="1" maxOccurs="1" type="xs:string"></xs:element>
            <xs:element name="controller" minOccurs="1" maxOccurs="1" type="xs:string"></xs:element>
            <xs:element name="action" minOccurs="1" maxOccurs="1" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== antunonline/azfcms/application/configs/descriptor/plugin/content/Redirector.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<plugin
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://it-branch.com/xml/ns/plugin/content'
    xsi:schemaLocation='http://it-branch.com/xml/ns/plugin/content file:/var/www/azfcms/library/Azf/Plugin/Descriptor/Parser/Content.xsd'>
    <pluginIdentifier>redirector</pluginIdentifier>
    <displayName>URL Redirector</displayName>
    <description>Redirect the user to specified URL</description>
    <version>1.0</version>
    <module>default</module>
    <controller>redirector</controller>
    <action>render</action>

</plugin>

=== antunonline/azfcms/application/configs/descriptor/plugin/content/DijitEditor.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:plugin
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://it-branch.com/xml/ns/plugin/content'
    xsi:schemaLocation="http://it-branch.com/xml/ns/plugin/content /var/www/azfcms/library/Azf/Plugin/Descriptor/Parser/Content.xsd"
>
    
    <ns1:pluginIdentifier>dijitEditor</ns1:pluginIdentifier>
    <ns1:displayName>Dijit Editor</ns1:displayName>
    <ns1:description>WYSIWYG editor that uses dijit Editor widget for editing</ns1:description>
    <ns1:version>1.0</ns1:version>
    <ns1:module>default</ns1:module>
    <ns1:controller>dijiteditor</ns1:controller>
    <ns1:action>produce</ns1:action>
    
</ns1:plugin>
